### ISSUE TITLE
"slow" movement 

### ISSUE THREAD

**Issue by 22chrs** [luni64/TeensyStep4#19]
Hi! 
I really love the TeensyStep Lib. Sad story, that it is quite difficult to get teensy 3.5.
So I tried the new one! (Thanks a lot!) but it seems to be quiet slow? 

I run a 256 TMC2209 via 256 micro stepping at a 200 resolution stepper. Without any load I get a little bit less than 2 revolutions per second. Sams stepper is way faster with the TMC2209 nativ velocity function which drives it via UART. 

Is it possibly since the teensy 4.1 should be way faster than the 3.5?

**Comment by luni64** [comment]
Actually, as mentioned in the Readme the library is just a quick and dirty experiment. It needs a complete rewrite, but I currently don't find time for this. 

> Is it possibly since the teensy 4.1 should be way faster than the 3.5?

Unfortunately the interrupt system of the T4 is not much faster that the one on the T3.5/6. This is due to synchronization issues between the internal busses which run on different speeds. See here for more information on this: https://forum.pjrc.com/index.php?threads/teensy-4-intervaltimer-max-speed.57959/#post-218567

**Comment by 22chrs** [comment]
Thanks for your fast reply! I know that you don't find the time at the moment. That is perfectly fine. :) 
Maybe I get things done be myself. For a start, where would you look for to fix the issue in the experimental TeensyStep4? 
With the current setup I get approximately 100.000 steps per second. (I aim for the 300.000 which are possible with the Teensy 3.5)

PS: I just noticed that you also live in Germany. I am working on this:
https://www.instagram.com/hejtoto/

**Comment by luni64** [comment]
> For a start, where would you look for to fix the issue in the experimental TeensyStep4?

TeensyStep4 uses the 16bit TMR timers instead of the 32bit PIT modules I used for the T3x boards. That would allow for a dedicated timer for nearly each pin (not yet implemented) Thus, the annoying 4 timer limit of the old lib would be gone. However, since the timers are 16bit only one needs to play with the prescaler.   
Currently you can only choose a fixed prescaler value (default: 5). You can change that here:

https://github.com/luni64/TeensyStep4/blob/42e1f69450902c7f96d7cd11ab079036adc36d18/src/timers/Teensy4/TMR/TMR.h#L29

Choosing a smaller value would increase both, the max as well as the min speed of the motors. Hope that helps. 

Nice project by the way!

**Comment by 22chrs** [comment]
Nice! Thanks a lot. That worked! Lowering the  prescale = 4 and at the same time setting a 70.000 steps/s speed limit worked fine for my tmc2209 at 256 microstepping, while keeping the noise low and increasing speed of the stepper to 3 turns per second. More would be possible, but the noise of the stepper increases and now the limit is the stepper, which can't handle too many steps/s, which the lib now delivers. 👍

**Comment by luni64** [comment]
Great, have fun
